### ISSUE TITLE
TODO (due : 11/12)

### ISSUE THREAD

**Issue by jeeyung** [jeeyung/word_embedding#2]
* 성원, 지민 

- [ ] similarity test dataset preprocess

- [ ] character level embedding evaluation 

* 지영, 형욱

- [ ] dataset preprocess 추가 (counter, Negative sampling)

- [ ] multi processing 구현

- [ ] 평가 결과보고 모델 수정

- [ ] 텐서보드 임베딩
